### ISSUE TITLE
Make top menu clickable a:href

### ISSUE THREAD

**Issue by benckx** [benckx/elephantchess.io#81]
Try this solution

```css
a {
    display: block;
}
```

from https://stackoverflow.com/questions/796087/make-a-div-into-a-link
